version: "3.8"

services:
  next-app:
    env_file:
      - devcontainer.env
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/app/workspace
      - ~/.config/gcloud/application_default_credentials.json:/secrets/gcloud/credentials.json
      - node_modules:/app/workspace/node_modules

    networks:
      devnet: {}

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - 5432:5432
    networks:
      devnet: {}

volumes:
  node_modules:

networks:
  devnet:
